name = "LocalREPLHistory"
uuid = "9ad053a0-9fed-11e9-2d80-1135272482b0"
authors = ["p1scescom <piscesuoza0317@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
